### ISSUE TITLE
ignoredApps configuration ignored

### ISSUE THREAD

**Issue by fharper** [gleich/nuke#39]
## Description

I have a `config.yml` in `~/.config/nuke/` which is detected as it doesn't check for updates anymore, but the applications listed with `ignoredApp` aren't ignored. I may be doing something wrong!

## Steps to reproduce

I'm running the `nuke` command in the terminal. It is working, just not taking the `ignoreApps` part of my configuration file. Here is my configuration file:

```yaml 
ignoredUpdates: true
ignoredApps:
  - Brave Browser
  - iTerm
  - Little Snitch
  - OBS
  - Sound Control
```
